### ISSUE TITLE
Can we create good scripts to facilitate the construction of surfaces easily?

### ISSUE THREAD

**Issue by logsdail** [logsdail/software#11]
Bare in mind we don't want to reinvent functionality of ASE or PyMatGen, but we do want to make it easy to use these...?

**Comment by logsdail** [comment]
Formalised functionality to create a range of surface facets. Do we need something that will create all surface facets that are not symmetry equivalent?

**Comment by logsdail** [comment]
@kush2803 - let me know your thoughts on this, as it's your code that is being debugged!

**Comment by kush2803** [comment]
I have made added the descriptions wherever required. 
I am not sure about the non-symmetric facets. If you think that will be a good addition to the script, then we can add that. But does that require a different kind of bulk input file?

**Comment by logsdail** [comment]
Yes - anything non cubic would have this requirement, I think. Gets a bit complicated but can look if actually needed.

**Comment by kush2803** [comment]
Then I would not worry about that. If need be, we can create a different script for that. That way both the script do not get too complicated and are easy to understand.

**Comment by logsdail** [comment]
Surface structures now sensible and rigorously tested.
